DOMAIN = "alternative_time"

CONF_NAME = "name"
CONF_TIMEZONE = "timezone"
CONF_ENABLE_TIMEZONE = "enable_timezone"
CONF_ENABLE_STARDATE = "enable_stardate"
CONF_ENABLE_SWATCH = "enable_swatch"
CONF_ENABLE_UNIX = "enable_unix"
CONF_ENABLE_JULIAN = "enable_julian"
CONF_ENABLE_DECIMAL = "enable_decimal"
CONF_ENABLE_HEXADECIMAL = "enable_hexadecimal"
CONF_ENABLE_MAYA = "enable_maya"
CONF_ENABLE_NATO = "enable_nato"
CONF_ENABLE_NATO_ZONE = "enable_nato_zone"
CONF_ENABLE_NATO_RESCUE = "enable_nato_rescue"

DEFAULT_NAME = "Alternative Time"